<a href="https://colab.research.google.com/github/Taheri1400/data_analysing_Pandas_numpy_projects/blob/main/final_project_4_rfm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
ارزش‌گذاری مشتریان
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font>
    در ادامه‌ی امور مربوط به بازاریابی، در این گام باید براساس ارزش مشتریان برای شرکت اقدام به گروه‌بندی آن‌ها کنید.
    برای این کار از یک روش معروف حوزه‌ی تحلیل رفتار مشتری با نام <a href="https://en.wikipedia.org/wiki/RFM_(market_research)"><i>RFM</i></a> استفاده خواهید کرد.
    در این روش برای هر مشتری سه معیار محاسبه می‌شود:
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font>
    <ol>
        <li>
            <b>معیار <i>Recency</i> (ماندگاری):</b> تعداد روزی که از آخرین خرید مشتری می‌گذرد.
        </li>
        <li>
            <b>معیار <i>Frequency</i> (فرکانس):</b> تعداد دفعاتی که مشتری از ما خرید کرده است.
        </li>
        <li>
            <b>معیار <i>Monetary Value</i> (ارزش مالی):</b> مجموع درآمدی که شرکت از یک مشتری داشته است.
        </li>
    </ol>
</font>
</div>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font>
این معیارها، نشان‌دهنده‌ی شاخص‌های مهمی در رفتار مشتریان هستند. به‌عنوان مثال، هرچه خرید جدیدتری توسط یک مشتری صورت گرفته باشد، احتمال آن‌که وی مجدد از ما خرید کند، افزایش می‌یابد. هرچه مشتری تعداد دفعات بیشتری خرید کند، به این معنی‌ست که مشتری رضایت بیشتری دارد و همچنین میزان درآمدی که یک مشتری برای شرکت تولید می‌کند، می‌تواند او را از سایر خریداران متمایز کند.
</font>
</p>

   
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
کتابخانه‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
       ابتدا کتابخانه‌های مورد نیاز خود را فرا بخوانید.
</font>
</p>

In [3]:
import pandas as pd

In [1]:
!pip install matplotlib==3.9.2 numpy==2.1.2

Collecting matplotlib==3.9.2
  Downloading matplotlib-3.9.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting numpy==2.1.2
  Downloading numpy-2.1.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.9.2) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib==3.9.2) (1.17.0)
Downloading matplotlib-3.9.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 62.1 MB/s eta 0:00:00
Downloading numpy-2.1.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 79.3 MB/s eta 0:00:00
Installing collected packages: numpy, matplotlib
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.10.0
    Uninstalling matplotlib-3.10.0:
      Successfully uninstalled matplotlib-3.10.0
Successfully installed matplotlib-3.9.2 numpy-2.1.2

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    حال داده‌های پیش‌پردازش‌شده را که در گام اول پروژه در فایل <code>preprocessed_sales.csv</code> ذخیره کردید به شکل یک دیتافریم بخوانید.
</font>
</p>

In [4]:
df =pd.read_csv('/content/drive/MyDrive/df_no_canceled_invoice.csv')
df.head()

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    معیار Recency
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    ابتدا نیاز است برای هر مشتری (<code>CustomerId</code>) معیار <i>Recency</i> را محاسبه کنید.
    برای این معیار باید تعداد روز گذشته از آخرین خرید کاربر نسبت به یک روز بعد از آخرین تاریخ موجود در مجموعه‌داده (ستون <code>InvoiceDate</code>) را محاسبه کنید. زیرا که فرض را بر آن گرفته‌ایم که شما در چنین روزی در حال تحلیل هستید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    بنابراین ابتدا آخرین تاریخ موجود در مجموعه‌داده را پیدا کرده، و پس از جمع روز آن با <code>1</code>، حاصل را در متغیر <code>last_day</code> ذخیره کنید.
    مقدار این متغیر باید از نوع <code>Timestamp</code> باشد. به‌عنوان مثال اگر آخرین تاریخ معادل <code>Timestamp('2010-10-10 10:10:00')</code> بود، آن‌گاه حاصل شما باید به شکل <code>Timestamp('2010-10-11 10:10:00')</code> باشد.
</font>
</p>

In [6]:
from datetime import datetime

In [7]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [8]:
last_day = df['InvoiceDate'].max()+pd.Timedelta(days=1)
last_day

Timestamp('2010-12-10 20:01:00')

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اکنون می‌توانید به ازای هر مشتری، تاریخ آخرین خرید وی را پیدا کرده و تعداد روز گذشته از <code>last_day</code> را محاسبه کنید.
    <br>
    حاصل را در یک دیتافریم به نام <code>df_customer_segments</code> و با دو ستون <code>CustomerId</code> (شناسه‌ی مشتری) و <code>Recency</code> (مقدار ماندگاری محاسبه‌شده) ذخیره کنید. همچنین دقت کنید، دیتافریم <code>df_customer_segments</code> باید بر اساس ستون <code>CustomerId</code> (شناسه‌ی مشتری) مرتب‌سازی شده باشد.
</font>
</p>

In [17]:
df_customer=df.groupby('CustomerId')['InvoiceDate'].max().reset_index()
df_customer['Recency']=(last_day - df_customer['InvoiceDate']).dt.days

In [19]:
df_customer_segments=df_customer[['CustomerId','Recency']].sort_values('CustomerId').reset_index(drop=True)

In [20]:

df_customer_segments.head()

   CustomerId  Recency
0     12346.0      165
1     12347.0        3
2     12348.0       74
3     12349.0       43
4     12351.0       11

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    معیار Frequency
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اکنون باید محاسبه کنید هرکدام از مشتری‌ها تاکنون چند خرید <b>یکتا</b> داشته‌اند. حاصل را در ستونی به نام <code>Frequency</code> به دیتافریم <code>df_customer_segments</code> اضافه کنید.
</font>
</p>

In [21]:
frequency=df.groupby('CustomerId')['InvoiceNumber'].nunique()

In [22]:
frequency

CustomerId
12346.0    11
12347.0     2
12348.0     1
12349.0     3
12351.0     1
           ..
18283.0     6
18284.0     1
18285.0     1
18286.0     2
18287.0     4
Name: InvoiceNumber, Length: 4312, dtype: int64

In [23]:
df_customer_segments['Frequency'] = df_customer_segments['CustomerId'].map(frequency)
df_customer_segments.head()

   CustomerId  Recency  Frequency
0     12346.0      165         11
1     12347.0        3          2
2     12348.0       74          1
3     12349.0       43          3
4     12351.0       11          1

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    معیار Monetary Value
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    برای این معیار باید محاسبه کنید مجموع خرید هر مشتری چقدر بوده است؟ توجه داشته باشید که برای محاسبه‌ی دریافتی هر ردیف باید قیمت واحد (<code>UnitPrice</code>) را در تعداد آن (<code>Quantity</code>) ضرب کنید و از حاصل آن برای محاسبه‌ی مجموع خرید هر مشتری استفاده کنید.
     حاصل را در ستونی به نام <code>MonetaryValue</code> به دیتافریم <code>df_customer_segments</code> اضافه کنید.
</font>
</p>

In [24]:
df['sell']=df['UnitPrice']*df['Quantity']

In [25]:
sell=df.groupby('CustomerId')['sell'].sum()

In [26]:
df_customer_segments['MonetaryValue'] = df_customer_segments['CustomerId'].map(sell)
df_customer_segments.head()

   CustomerId  Recency  Frequency  MonetaryValue
0     12346.0      165         11         372.86
1     12347.0        3          2        1323.32
2     12348.0       74          1         222.16
3     12349.0       43          3        2671.14
4     12351.0       11          1         300.93

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    گروه‌بندی هر معیار
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اکنون نیاز است هرکدام از این سه معیار را براساس چارک اول،‌ دوم و سوم به شکل زیر به ۴ گروه مختلف تقسیم کنید
    (برای یادآوری مفهوم چارک،
    <a href="https://fa.wikipedia.org/wiki/%DA%86%D8%A7%D8%B1%DA%A9_(%D8%A2%D9%85%D8%A7%D8%B1)">این مطلب</a>
    را از ویکی‌پدیای فارسی بخوانید).
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

| <b>شماره گروه</b> | <b>شرط</b> |
| :---: | :---: |
| 1 | <code dir=ltr>value <= Q1</code> |
| 2 | <code dir=ltr>Q1 < value <= Q2</code> |
| 3 | <code dir=ltr>Q2 < value <= Q3</code> |
| 4 | <code dir=ltr>Q3 < value</code> |

</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    به ازای هر کدام از این سه معیار چنین کاری را انجام داده و نتایج را در سه ستون دیگر به نام‌های
    <code>F_quartile</code>، <code>R_quartile</code> و <code>M_quartile</code>
    ذخیره کنید.
    توجه کنید که مقادیر این ستون‌ها معادل شماره گروه یعنی اعداد <code>1</code> تا <code>4</code> خواهد بود.
</font>
</p>

In [34]:
import numpy as np

In [35]:

labels=[1,2,3,4]

In [36]:
FQ1=df_customer_segments['Frequency'].quantile(.25)
FQ2=df_customer_segments['Frequency'].quantile(.5)
FQ3=df_customer_segments['Frequency'].quantile(.75)

In [37]:
RQ1=df_customer_segments['Recency'].quantile(.25)
RQ2=df_customer_segments['Recency'].quantile(.5)
RQ3=df_customer_segments['Recency'].quantile(.75)

In [38]:
MQ1=df_customer_segments['MonetaryValue'].quantile(.25)
MQ2=df_customer_segments['MonetaryValue'].quantile(.5)
MQ3=df_customer_segments['MonetaryValue'].quantile(.75)

In [39]:
bins_M=[-np.inf, MQ1, MQ2, MQ3, np.inf]
bins_F=[-np.inf, FQ1, FQ2, FQ3, np.inf]
bins_R=[-np.inf, RQ1, RQ2, RQ3, np.inf]

In [42]:
df_customer_segments['R_quartile'] = pd.cut(df_customer_segments['Recency'],bins=bins_R,labels=labels,include_lowest=True).astype(int)
df_customer_segments['F_quartile'] = pd.cut(df_customer_segments['Frequency'],bins=bins_F,labels=labels,include_lowest=True).astype(int)
df_customer_segments['M_quartile'] =  pd.cut(df_customer_segments['MonetaryValue'],bins=bins_M,labels=labels,include_lowest=True).astype(int)
df_customer_segments.head()

,CustomerId,Recency,Frequency,MonetaryValue,R_quartile,F_quartile,M_quartile
0,12346.0,165,11,372.86,4,4,2
1,12347.0,3,2,1323.32,1,2,3
2,12348.0,74,1,222.16,3,1,1
3,12349.0,43,3,2671.14,2,3,4
4,12351.0,11,1,300.93,1,1,1

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    معیار RFM
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اکنون می‌توانید با کنار هم قرار دادن مقادیر ستون‌های
    <code dir=ltr>[R_quartile, F_quartile, M_quartile]</code>
    مقدار نهایی <i>RFM</i> را محاسبه کرده و در ستونی به همین نام ذخیره کنید.
    به‌‌عنوان مثال اگر مقادیر این ستون‌ها برای یک مشتری برابر
    <code dir=ltr>[1, 2, 3]</code> بود،
    آن‌گاه مقدار نهایی <i>RFM</i> برابر با <code>123</code> است.
</font>
</p>

In [43]:
df_customer_segments['RFM'] = (
    df_customer_segments['R_quartile'].astype(str) +
    df_customer_segments['F_quartile'].astype(str) +
    df_customer_segments['M_quartile'].astype(str)
).astype(int)

df_customer_segments.head()

,CustomerId,Recency,Frequency,MonetaryValue,R_quartile,F_quartile,M_quartile,RFM
0,12346.0,165,11,372.86,4,4,2,442
1,12347.0,3,2,1323.32,1,2,3,123
2,12348.0,74,1,222.16,3,1,1,311
3,12349.0,43,3,2671.14,2,3,4,234
4,12351.0,11,1,300.93,1,1,1,111

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    گروه‌بندی مشتریان
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    حال باید براساس مقادیر ستون <code>RFM</code> و طبق جدول زیر به گروه‌بندی مشتریان بپردازید و نام گروه آن‌ها را در ستونی به نام <code>Segment</code> ذخیره کنید.
    توجه داشته باشید که در این جدول، <code>X</code> به معنی هر مقداری است. به‌عنوان مثال <code>14X</code> به معنی <code>141</code>، <code>142</code>، <code>143</code> و <code>144</code> است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

| <b>Segment</b> | <b>RFM</b> |
| :---: | :---: |
| Best | <code dir=ltr>144</code> |
| AlmostLost | <code dir=ltr>344</code> |
| LostBigSpenders | <code dir=ltr>444</code> |
| LostCheap | <code dir=ltr>441</code> |
| Loyal | <code dir=ltr>X4X</code> |
| BigSpenders | <code dir=ltr>XX4</code> |

</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    <span style="color:purple"><b>نکته ۱:</b></span>
    در صورتی‌که یک مشتری در هیچ‌یک از گروه‌های جدول قرار نگرفت، گروه او را Normal اعلام کنید.
    <br>
    <span style="color:purple"><b>نکته ۲:</b></span>
    همچنین اگر یک RFM می‌تواند در دو گروه از جدول قرار بگیرد، اولویت با گروهی‌ست که در جدول، <b>بالاتر</b> آمده باشد.
</font>
</p>

In [44]:
import numpy as np

rfm = df_customer_segments['RFM'].astype(str)

conditions = [
    rfm == '144',
    rfm == '344',
    rfm == '444',
    rfm == '441',
    rfm.str[1] == '4',  # X4X
    rfm.str[2] == '4'   # XX4
]

segments = [
    'Best',
    'AlmostLost',
    'LostBigSpenders',
    'LostCheap',
    'Loyal',
    'BigSpenders'
]

df_customer_segments['Segment'] = np.select(
    conditions,
    segments,
    default='Normal'
)

df_customer_segments.head()

,CustomerId,Recency,Frequency,MonetaryValue,R_quartile,F_quartile,M_quartile,RFM,Segment
0,12346.0,165,11,372.86,4,4,2,442,Loyal
1,12347.0,3,2,1323.32,1,2,3,123,Normal
2,12348.0,74,1,222.16,3,1,1,311,Normal
3,12349.0,43,3,2671.14,2,3,4,234,BigSpenders
4,12351.0,11,1,300.93,1,1,1,111,Normal

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [46]:
import zipfile
import joblib

df_customer_segments.to_csv('df_customer_segments.csv', index=False)
joblib.dump(last_day, 'last_day')

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["last_day", "df_customer_segments.csv"]
compress(file_names)

File Paths:
['last_day', 'df_customer_segments.csv']