<a href="https://colab.research.google.com/github/Taheri1400/data_analysing_Pandas_numpy_projects/blob/main/pushe_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پوشه
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    هدف این تمرین، دوره کردن مطالب درسنامه‌های قبلی  به کمک تحلیل داده‌های پوشه است.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
   نوتیفیکیشن چیست؟
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
  نوتیفیکیشن یا همان پوش نوتیفیکیشن، یک راه ارتباطی بین مالک اپلیکیشن موبایل یا وب با کاربرانش است. نوتیفیکیشن این اجازه را می‌دهد که صاحب اپلیکیشن خبر یا اتفاقی جدید را به کاربران خود برساند؛ حتی اگر در آن هنگام کاربر در حال استفاده از اپلیکیشن نباشد.
برای مثال، توسعه‌دهنده می‌خواهد به کاربران خود بگوید که اپلیکیشن را آپدیت کنند؛ در این صورت، توسعه‌دهنده می‌تواند به راحتی از طریق نوتیفیکیشن این اطلاع را به کاربران خود بدهد و هم‌چنین لینک آپدیت را در آن قرار دهد.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
   پوشه چیست؟
    </font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    پوشه یک سرویس ارسال پوش نوتیفیکیشن برای نرم افزارهای موبایل و وب است. کسب‌وکارها و توسعه‌دهندگان موبایل و وب به هنگام نوشتن برنامه،
    از
    <i>SDK</i>
     پوشه در نرم‌افزار خودشان استفاده می‌کنند تا از طریق آن نرخ بازگشت و میزان درگیر‌شدن کاربران‌شان با برنامه را افزایش دهند و از آمار و فیلترهایی که پوشه در اختیارشان قرار می‌دهد برای بهبود برنامه و افزایش رضایت کاربران بهره ببرند.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
توضیح داده
</font>
</h2>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    داده‌ای که در اختیار شما قرار گرفته، حاوی اطلاعاتی از نوتیفیکیشن‌هایی است که به تلفن همراه کاربران ارسال شده‌ است.
    <br>
    هر سطر از این دیتافریم مشخص می‌کند چه نوتیفیکیشنی، در چه زمانی، توسط چه برنامه‌ای به چه کاربری فرستاده شده‌ است و واکنش کاربر نسبت به آن چه بوده‌ است.
    در جدول زیر ستون‌های داده‌ای که در فایل
    <code>notifications_pushe.csv</code>
    موجود است را بررسی می‌کنیم.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<center>

| ستون | توضیح |
|:-----------:|:------:|
| action |کلیک کردن (<code>C</code>)، رد کردن (<code>F</code>)|
| application_id | شناسه‌ی برنامه|
| interaction_time |زمان دریافت پیام|
| notification_id | شناسه‌ی نوتیفیکیشن|
| user_id | شناسه‌ی کاربر|

</center>
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span color=”purple”><b>توجه:</b></span>
    عددی که در ستون <code>interaction_time</code> آمده‌ است بر حسب ثانیه است. این عدد نشان می‌دهد چند ثانیه از تاریخ <b>۲۰۱۹/۶/۱</b> گذشته است.
       به عنوان مثال، زمان ۵۲۵۸۷۰۰ به معنی گذشتن ۵۲۵۸۷۰۰ ثانیه از ۲۰۱۹/۶/۱ است.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
بخش اول: پیش‌پردازش
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در این مرحله باید با استفاده از ستون <code>interaction_time</code> و تاریخ <b>۲۰۱۹/۶/۱</b>، تاریخی که نوتیفیکیشن ارسال شده‌ است را به‌دست آوریم.
    تاریخی که نوتیفیکیشن ارسال شده‌ است را در ستون جدیدی به اسم
    <code>date</code>
    به دیتافریم اضافه کنید. در قسمت زیر، مثالی برای به‌دست‌آوردن تاریخ آورده شده است و انتظار می‌رود تاریخی که شما به‌دست می‌آورید نیز از جنس
    <code>datetime</code>
    باشد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span color=”green”><b>    راهنمایی : معرفی تابع <code>timedelta</code></b></span>
<br>
   این تابع برای نشان دادن فاصله‌ی زمانی به کار می‌رود. مثلا اگر بخواهیم بدانیم ۱۰ روز و ۵۰ ثانیه بعد از زمانی که در متغیر <code>example_time</code> ذخیره شده‌ است، چه زمانی است می‌توانیم به شکل زیر عمل کنیم.
</font>
</p>

In [1]:
import datetime
from datetime import timedelta

example_time = datetime.datetime(2021,9,21)
example_time + timedelta(days=10, seconds=50)

datetime.datetime(2021, 10, 1, 0, 0, 50)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
   اگر بخواهیم بدانیم ۱۰ روز و ۵۰ ثانیه قبل از زمانی که در متغیر <code>example_time</code> ذخیره شده‌ است، چه زمانی است می‌توانیم به شکل زیر عمل کنیم.
</font>
</p>

In [2]:
example_time - timedelta(days=10, seconds=50)

datetime.datetime(2021, 9, 10, 23, 59, 10)

In [42]:
from google.colab import files
uploaded=files.upload()

Saving notifications_pushe.csv to notifications_pushe.csv

In [7]:
import pandas as pd
# TODO: read csv file in df
df = df = pd.read_csv('/content/drive/MyDrive/data/notifications_pushe.csv')
df

       action  application_id  interaction_time  notification_id  user_id
0           F               1           4489200               79      665
1           F               1           4489200               79     6280
2           F               1           4388400               78    14774
3           F               1           4410000               78     3152
4           C               1           4410000               72     3633
...       ...             ...               ...              ...      ...
140723      F               0            993600               13    14760
140724      F               0            928800               13     2096
140725      F               0            900000               13    11308
140726      F               0            885600               13     5975
140727      F               0            907200               13    15272

[140728 rows x 5 columns]

In [8]:
# TODO: calculate date and add it to dateframe as a new column
from datetime import datetime, timedelta

df['date'] = df['interaction_time'].apply(
    lambda x: datetime(2019, 6, 1) + timedelta(seconds=x)
)
df

,action,application_id,interaction_time,notification_id,user_id,date
0,F,1,4489200,79,665,2019-07-22 23:00:00
1,F,1,4489200,79,6280,2019-07-22 23:00:00
2,F,1,4388400,78,14774,2019-07-21 19:00:00
3,F,1,4410000,78,3152,2019-07-22 01:00:00
4,C,1,4410000,72,3633,2019-07-22 01:00:00
...,...,...,...,...,...,...
140723,F,0,993600,13,14760,2019-06-12 12:00:00
140724,F,0,928800,13,2096,2019-06-11 18:00:00
140725,F,0,900000,13,11308,2019-06-11 10:00:00
140726,F,0,885600,13,5975,2019-06-11 06:00:00
140727,F,0,907200,13,15272,2019-06-11 12:00:00

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
بخش دوم: تحلیل اپلیکیشن‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در این بخش می‌خواهیم بدانیم کدام اپلیکیشن، در ارسال نوتیفیکیشن‌ موفق‌ عمل کرده است.
    <br>
    <br>
    به ازای هر اپلیکیشن، نرخ کلیک‌‌شدن نوتیفیکیشن‌ها را به دست آورید. به عنوان مثال اگر اپلیکیشن شماره‌ی ۱۰، از مجموع ۱۰۰ نوتیفیکیشنی که ارسال کرده‌ است، ۱۰ نوتیفیکیشن توسط کاربران کلیک شده‌ باشد، نرخ کلیک‌‌شدن نوتیفیکیشن‌های اپلیکیشن‌ شماره ۱۰، عدد ۰/۱ خواهد بود.
    موفق‌ترین اپلیکیشن، اپلیکیشنی است که نرخ کلیک‌‌شدن نوتیفیکیشن‌هایش از همه بیشتر باشد.
    جنس داده نرخ کلیک از نوع
    <code>
    np.float</code> می‌باشد.
    <br>
    موفق‌ترین اپلیکیشن‌ را به همراه نرخ‌ کلیک‌‌شدنش در تاپلی به اسم <code>tuple_appid_successrate</code> ذخیره کنید. به صورتی که عنصر اول تاپل، شناسه‌ی اپلیکیشن موفق و عنصر دوم تاپل، نرخ کلیک‌‌شدن نوتیفیکیشن‌هایش باشد.
    اعدادی که در مثال بالا اشاره شد، هیچ اعتباری ندارند و کاملا تصادفی تولید شده‌اند. بنابراین جوابی که شما به دست خواهید‌ آورد، ممکن است با این اعداد تفاوت داشته باشد.
</font>
</p>

In [9]:
# TODO: find (app_id, success_rate)
df1 = df.copy()

df1['clicked'] = (df1['action'] == 'C')

success_rate = df1.groupby('application_id')['clicked'].mean()

success_rate
best_app = success_rate.idxmax()
best_rate = success_rate.max()

tuple_appid_successrate = (best_app, best_rate)
tuple_appid_successrate

(np.int64(1), 0.18529923416848293)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
بخش سوم: تحلیل نوتیفیکیشن‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در این بخش می‌خواهیم بدانیم کدام نوتیفیکیشن در کلیک‌‌شدن موفق ظاهر شده‌ است و در چه روزی از هفته، بیشترین میزان کلیک را داشته است. در این بخش هم همانند بخش دوم معیار موفقیت ما
     <b>نرخ کلیک شدن یک نوتیفیکشن </b>
     است.
     جنس داده نرخ کلیک از نوع
    <code>
    np.float</code> می‌باشد.
    <br>
    <br>
    ابتدا فرض کنید که بین تمام نوتیفیکیشن‌ها، نوتیفکیشینی با شناسه‌ی ۱۱۰۰ بیشترین نرخ کلیک‌شدن را داشته باشد. در این صورت، نوتیفیکیشن ۱۱۰۰ موفق‌ترین نوتیفیکیشن است.
    حال فرض کنید که این نوتیفیکیشن در روز شنبه ۱۰۰ کلیک، یکشنبه ۱۳۰ کلیک، دوشنبه ۳۰ کلیک، سه‌شنبه ۹۰ کلیک، چهارشنبه ۴۵ کلیک، پنج‌شنبه ۴ کلیک و جمعه هیچ‌ کلیکی نداشته باشد.
    در این صورت، یکشنبه (Sunday) روزی است که نوتیفیکیشن ۱۱۰۰، بیش‌ترین کلیک‌ را خورده است.
     بنابراین تاپل
     <code>tuple_notifid_day</code>
      به صورت زیر باید مقداردهی شود.  
</font>
</p>

```python
tuple_notifid_day = (1100, "Sunday")
```
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
   ضمناً توجه کنید که اسامی روز‌ها باید بر اساس نام انگلیسی آن‌ها باشد.
    مانند مثال بالا، برای روز یکشنبه کلمه‌ی Sunday، روز دوشنبه کلمه‌ی Monday و ... در نظر بگیرید.
</font>
</p>

In [15]:
# TODO: find (id, day)
# نرخ کلیک هر نوتیفیکیشن
notif_rate = df.groupby('notification_id')['action'].apply(
    lambda x: (x == 'C').mean()
)

# شناسه موفق‌ترین نوتیفیکیشن
best_notif = notif_rate.idxmax()

# فقط ردیف‌های کلیک‌شده مربوط به آن نوتیفیکیشن
clicked = df[
    (df['notification_id'] == best_notif) &
    (df['action'] == 'C')
].copy()

# نام روز هفته
clicked['day'] = clicked['date'].dt.day_name()

# روزی که بیشترین کلیک را داشته
best_day = clicked['day'].value_counts().idxmax()

tuple_notifid_day = (best_notif, best_day)

tuple_notifid_day

(np.int64(79), 'Monday')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
بخش چهارم: تحلیل روز‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
   هدف بخش چهارم آن است که بدانیم در چه روز‌هایی از ماه، نرخ کلیک‌‌شدن نوتیفیکیشن‌ها بیشتر است.
    <br>
    <br>
    به عبارت ساده‌تر، دیتافریم را بر اساس روزی که نوتیفیکیشن ارسال شده‌ است، گروه‌بندی کنید؛ سپس محاسبه کنید در هر روز، نرخ کلیک‌‌شدن نوتیفیکیشن‌ها چه‌مقدار بوده‌ است.
    در نهایت روزی که بیش‌ترین نرخ را دارد به همراه نرخ آن روز، در تاپلی به اسم <code>tuple_day_rate</code> ذخیره کنید.
    به عنوان مثال اگر روز ۱۵ ام دارای نرخ ۰/۸۵ باشد (بیش‌ترین نرخ در بین همه ۳۰ روز)، تاپل <code>tuple_day_rate</code> را مانند زیر مقداردهی کنید.
</font>
</p>

```python
tuple_day_rate = (15, 0.85)
```

In [40]:
df2=df.copy()
df2['day']=df2['date'].dt.day


notid_day=df2.groupby('day')['action'].apply(lambda x: (x=='C').mean())
success_day_rate=notid_day.max()
success_day=notid_day.idxmax()
tuple_day_rate = (success_day,success_day_rate)
tuple_day_rate

(np.int32(22), 0.26486013986013984)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [41]:
import zipfile
import joblib

df[['date']].to_csv('date.csv', index=False)
joblib.dump(tuple_appid_successrate,"tuple_appid_successrate")
joblib.dump(tuple_notifid_day, 'tuple_notifid_day')
joblib.dump(tuple_day_rate, 'tuple_day_rate')

def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)


file_names = ["date.csv", "tuple_appid_successrate", "tuple_notifid_day", "tuple_day_rate"]
compress(file_names)

File Paths:
['date.csv', 'tuple_appid_successrate', 'tuple_notifid_day', 'tuple_day_rate']